version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    container_name: midtrans-frontend
    networks:
      - phising
  back-end:
    build:
      context: ./service
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    container_name: midtrans-service
    networks:
      - phising
networks:
  phising:
    driver: bridge